[package]
name = "minimap2"
version = "0.1.9"
edition = "2021"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Bindings to libminimap2"
repository = "https://github.com/jguhlin/minimap2-rs"
categories = ["science"]
keywords = ["bioinformatics", "fasta", "alignment", "fastq"]
exclude = [
  "**/*.fasta",
  "libsfasta/test_data/",
  "*.profdata",
  "*.mmi",
  "**/*.mmi",
  "minimap2-sys/",
]


[dependencies]
libc = "0.2.134"

simdutf8 = { version = "0.1.4", optional = true }

flate2 = { version = "1.0.17", features = [
  "zlib"
], default-features = false, optional = true }

# Dep for development
#minimap2-sys = { path = "./minimap2-sys" }
minimap2-sys = "0.1.7"

fffx = {version = "0.1.2", optional = true }
#fffx = { path = "../fffx", optional=true }
rust-htslib = { version = "0.40.2", optional = true }

[features]
default = ['map-file']
htslib = ['rust-htslib']
map-file = ['flate2', 'simdutf8', 'fffx']

# [profile.release]
# opt-level = 3
# lto = "fat"
# codegen-units  = 1

[profile.dev]
debug = true

[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
bitflags = "1.3.2"
cargo-nextest = "0.9.48"
