[package]
name = "minimap2-htslib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimap2 = {path= "..", version="0.1.9"}
rust-htslib = "0.40.2"
